package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// ============================================================================
// `dash show` no-arg and the default dashboard's two states (D-3, defect D67).
//
// Home Assistant's default dashboard is served auto-generated until something
// stores a config for it. On the wire (captured from HA 2026.7.4, see
// internal/integration/lovelace_oracle_test.go):
//
//   - auto-generated: `lovelace/config` fails with
//     {"code":"config_not_found","message":"No config found."}
//   - stored: `lovelace/config` returns the stored document.
//
// D-3: views summary when a stored config exists; when auto-generated, say
// exactly that and point to `dash ls`. Never fabricate a strategy render.
// `--json` must carry the same truth (H-10).
// ============================================================================

// configNotFound is the exact error envelope HA 2026.7.4 returns for the
// default dashboard in its auto-generated state (oracle-captured).
var configNotFound = wsErrorResponse{Code: "config_not_found", Message: "No config found."}

func withDashBoolFlag(t *testing.T, p *bool, v bool) {
	t.Helper()
	old := *p
	*p = v
	t.Cleanup(func() { *p = old })
}

func TestRunDashShow_AutoGeneratedDefaultReportsHonestly(t *testing.T) {
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": configNotFound,
	}, nil)
	withFlagDir(t, ts.dir)

	var buf bytes.Buffer
	if err := runDashShow(context.Background(), &buf, ""); err != nil {
		t.Fatalf("dash show must answer, not fail, for the auto-generated default: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "auto-generated") {
		t.Errorf("output must name the auto-generated state:\n%s", out)
	}
	if !strings.Contains(out, "dash ls") {
		t.Errorf("output must point to `dash ls`:\n%s", out)
	}
	// Never fabricate a strategy render: no views table, no counts.
	if strings.Contains(out, "cards") || strings.Contains(out, "masonry") {
		t.Errorf("output must not fabricate a views rendering:\n%s", out)
	}
}

func TestRunDashShow_AutoGeneratedDefaultJSONCarriesTheState(t *testing.T) {
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": configNotFound,
	}, nil)
	withFlagDir(t, ts.dir)
	withFlagJSON(t, true)

	var buf bytes.Buffer
	if err := runDashShow(context.Background(), &buf, ""); err != nil {
		t.Fatalf("dash show --json failed for the auto-generated default: %v", err)
	}
	var obj map[string]any
	if err := json.Unmarshal(buf.Bytes(), &obj); err != nil {
		t.Fatalf("--json did not produce strict JSON: %v\n%s", err, buf.String())
	}
	if obj["state"] != "auto-generated" {
		t.Errorf(`json state = %v, want "auto-generated"; a machine caller must be able to tell the states apart (H-10): %s`,
			obj["state"], buf.String())
	}
	if _, hasViews := obj["views"]; hasViews {
		t.Errorf("auto-generated json must not fabricate a views key: %s", buf.String())
	}
}

func TestRunDashShow_StoredDefaultJSONIsTheConfigDocument(t *testing.T) {
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": map[string]any{"views": []any{
			map[string]any{"title": "Stored", "path": "stored"},
		}},
	}, nil)
	withFlagDir(t, ts.dir)
	withFlagJSON(t, true)

	var buf bytes.Buffer
	if err := runDashShow(context.Background(), &buf, ""); err != nil {
		t.Fatalf("dash show --json failed for the stored default: %v", err)
	}
	var obj map[string]any
	if err := json.Unmarshal(buf.Bytes(), &obj); err != nil {
		t.Fatalf("--json did not produce strict JSON: %v\n%s", err, buf.String())
	}
	if _, hasViews := obj["views"]; !hasViews {
		t.Errorf("stored json must carry the config document: %s", buf.String())
	}
	// The discriminator: a stored answer never claims a lifecycle state.
	if _, hasState := obj["state"]; hasState {
		t.Errorf("stored json must not carry the auto-generated discriminator: %s", buf.String())
	}
}

func TestRunDashShow_StoredDefaultRendersViewsSummary(t *testing.T) {
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": map[string]any{"views": []any{
			map[string]any{"title": "Morning", "path": "morning", "cards": []any{map[string]any{"type": "markdown"}}},
		}},
	}, nil)
	withFlagDir(t, ts.dir)

	var buf bytes.Buffer
	if err := runDashShow(context.Background(), &buf, ""); err != nil {
		t.Fatalf("dash show failed for the stored default: %v", err)
	}
	out := buf.String()
	for _, want := range []string{"Morning", "morning"} {
		if !strings.Contains(out, want) {
			t.Errorf("views summary missing %q:\n%s", want, out)
		}
	}
}

func TestRunDashShow_AutoGeneratedDefaultRawRefuses(t *testing.T) {
	// --raw exists for round-trip editing; for the auto-generated default there
	// is no stored config to round-trip, so fabricating output would hand the
	// caller a document HA does not hold.
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": configNotFound,
	}, nil)
	withFlagDir(t, ts.dir)
	withDashBoolFlag(t, &flagDashRaw, true)

	var buf bytes.Buffer
	err := runDashShow(context.Background(), &buf, "")
	if err == nil {
		t.Fatalf("--raw must refuse for the auto-generated default, got output:\n%s", buf.String())
	}
	if !strings.Contains(err.Error(), "auto-generated") {
		t.Errorf("refusal must name the state, got: %v", err)
	}
}

// yamlDefaultListEntry is the dashboards/list entry a YAML-mode default
// produces, verbatim shape from HA 2026.7.4 (lovelace_oracle_test.go). Note:
// no `id` — YAML dashboards carry none on the wire.
func yamlDefaultListEntry() map[string]any {
	return map[string]any{
		"url_path": "lovelace", "title": "Overview", "mode": "yaml",
		"show_in_sidebar": true, "require_admin": false, "filename": "ui-lovelace.yaml",
	}
}

func TestRunDashDelete_YamlDashboardRefusedBothWays(t *testing.T) {
	// A YAML dashboard exists in configuration.yaml, not in the storage
	// collection; its list entry has no id, so the delete API has nothing to
	// address. Preview and confirm must agree on the refusal (H-2).
	for _, confirm := range []bool{false, true} {
		ts := startCmdServer(t, map[string]any{
			"lovelace/dashboards/list":   []any{yamlDefaultListEntry()},
			"lovelace/dashboards/delete": map[string]any{},
		}, nil)
		withFlagDir(t, ts.dir)
		withDashBoolFlag(t, &flagDashConfirm, confirm)

		var buf bytes.Buffer
		err := runDashDelete(context.Background(), &buf, "lovelace")
		if err == nil || !strings.Contains(err.Error(), "yaml") {
			t.Fatalf("confirm=%v: want a yaml-mode refusal, got err=%v output:\n%s", confirm, err, buf.String())
		}
		if n := ts.commandCount("lovelace/dashboards/delete"); n != 0 {
			t.Errorf("confirm=%v: delete was sent %d time(s), want 0", confirm, n)
		}
	}
}

func TestRunDashSave_YamlDefaultRefusedBothWays(t *testing.T) {
	// Saving to the default is how an auto-generated default becomes
	// storage-mode — but a YAML-pinned default refuses saves at HA
	// ("Not supported"), so the preview must refuse too (H-2).
	for _, confirm := range []bool{false, true} {
		ts := startCmdServer(t, map[string]any{
			"lovelace/dashboards/list": []any{yamlDefaultListEntry()},
			"lovelace/config/save":     map[string]any{},
		}, nil)
		withFlagDir(t, ts.dir)
		withDashBoolFlag(t, &flagDashConfirm, confirm)
		withDashSaveInput(t, `{"views":[]}`)

		var buf bytes.Buffer
		err := runDashSave(context.Background(), &buf, "")
		if err == nil || !strings.Contains(err.Error(), "YAML-mode") {
			t.Fatalf("confirm=%v: want a yaml-mode refusal, got err=%v output:\n%s", confirm, err, buf.String())
		}
		if n := ts.commandCount("lovelace/config/save"); n != 0 {
			t.Errorf("confirm=%v: save was sent %d time(s), want 0", confirm, n)
		}
	}
}

func TestRunDashReplace_YamlDashboardRefusedBothWays(t *testing.T) {
	for _, confirm := range []bool{false, true} {
		ts := startCmdServer(t, map[string]any{
			"lovelace/dashboards/list": []any{yamlDefaultListEntry()},
			"lovelace/config": map[string]any{"views": []any{
				map[string]any{"cards": []any{map[string]any{"entity": "sensor.old"}}},
			}},
			"lovelace/config/save": map[string]any{},
		}, nil)
		withFlagDir(t, ts.dir)
		withDashBoolFlag(t, &flagDashConfirm, confirm)

		var buf bytes.Buffer
		err := runDashReplace(context.Background(), &buf, "sensor.old", "sensor.new", "lovelace")
		if err == nil || !strings.Contains(err.Error(), "yaml") {
			t.Fatalf("confirm=%v: want a yaml-mode refusal, got err=%v output:\n%s", confirm, err, buf.String())
		}
		if n := ts.commandCount("lovelace/config/save"); n != 0 {
			t.Errorf("confirm=%v: save was sent %d time(s), want 0", confirm, n)
		}
	}
}

// withDashSaveInput points `dash save` at a temp file holding body.
func withDashSaveInput(t *testing.T, body string) {
	t.Helper()
	p := t.TempDir() + "/cfg.json"
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	old := flagDashFile
	flagDashFile = p
	t.Cleanup(func() { flagDashFile = old })
}

func TestRunDashShow_UnclassifiableDefaultFails(t *testing.T) {
	// Any lovelace/config failure other than config_not_found means hactl does
	// not know which state the default is in — that is an error, not a report.
	ts := startCmdServer(t, map[string]any{
		"lovelace/config": wsErrorResponse{Code: "error", Message: "boom"},
	}, nil)
	withFlagDir(t, ts.dir)

	var buf bytes.Buffer
	err := runDashShow(context.Background(), &buf, "")
	if err == nil {
		t.Fatalf("dash show must fail when the default cannot be classified, got:\n%s", buf.String())
	}
	if strings.Contains(buf.String(), "auto-generated") {
		t.Errorf("an unclassifiable default must not be reported as auto-generated:\n%s", buf.String())
	}
}
