package cmd

import (
	"errors"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/hemm-ems/hactl/internal/surfaceaudit"
	"github.com/hemm-ems/hactl/internal/testaudit"
	"github.com/spf13/cobra"
)

// declaredContracts is every positional contract args.go defines, by the name
// the runtime gives its closure. A command whose Args is anything else — nil
// (cobra's ArbitraryArgs, which accepts and discards), or a bare cobra
// validator, which counts arguments without ever looking at them — is a site.
//
// Matching on the constructor rather than on "Args != nil" is the point: the
// three defects this closes were all commands that *did* something with their
// arguments, and two of the three had an Args validator already.
var declaredContracts = map[string]bool{
	"takesNone":    true,
	"takes":        true,
	"takesAtLeast": true,
	"takesAtMost":  true,
	"takesBetween": true,
}

// contractOf names the constructor a command's Args came from, or "" when it
// came from somewhere else.
//
// The closure's runtime name carries its enclosing functions, and the compiler
// inlines the constructor into its caller, so the same contract appears as
// ".../internal/cmd.init.takes.func136" from a command declaration and as
// ".../internal/cmd.TestX.takes.func1" from a test. The constructor is
// therefore the element before the trailing funcN, never a fixed position from
// the front.
func contractOf(c *cobra.Command) string {
	if c.Args == nil {
		return ""
	}
	full := runtime.FuncForPC(reflect.ValueOf(c.Args).Pointer()).Name()
	if i := strings.LastIndex(full, "/"); i >= 0 {
		full = full[i+1:]
	}
	parts := strings.Split(full, ".")
	if len(parts) < 2 {
		return ""
	}
	name := parts[len(parts)-2]
	if !declaredContracts[name] {
		return ""
	}
	return name
}

// cobraBuiltin reports whether a command was generated by cobra rather than by
// this package: `help` and the `completion` subtree. They are excluded by name
// because cobra adds them lazily during ExecuteC, so whether they are in the
// tree depends on what ran before — and a surface whose site set depends on
// test order is not a surface.
func cobraBuiltin(c *cobra.Command) bool {
	path := c.CommandPath()
	return path == "hactl help" || path == "hactl completion" || strings.HasPrefix(path, "hactl completion ")
}

// walkTree calls fn for every command in the tree below (and including) root,
// skipping cobra's own generated commands.
func walkTree(root *cobra.Command, fn func(*cobra.Command)) {
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		if cobraBuiltin(c) {
			return
		}
		fn(c)
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
}

// undeclaredPositionalSites is the extractor: every command whose positional
// contract is not one of args.go's. It takes a root so the fixture test can
// feed it a tree it built itself — an extractor that has silently stopped
// matching passes forever while proving nothing, and this surface reaches zero
// when the rule holds, so a non-empty check cannot be the guard.
func undeclaredPositionalSites(root *cobra.Command) []surfaceaudit.Site {
	var sites []surfaceaudit.Site
	walkTree(root, func(c *cobra.Command) {
		if contractOf(c) != "" {
			return
		}
		note := "Args is nil: cobra accepts every positional and the command discards it"
		if c.Args != nil {
			note = "Args is " + runtime.FuncForPC(reflect.ValueOf(c.Args).Pointer()).Name() +
				": arity is counted, the arguments themselves are not checked"
		}
		sites = append(sites, surfaceaudit.Site{Key: c.CommandPath(), File: "cobra tree", Note: note})
	})
	return sites
}

// positionalSurface is a VIOLATION surface: its sites are the commands that
// break H-22, so empty is the goal.
func positionalSurface() surfaceaudit.Surface {
	return surfaceaudit.Surface{
		Name:       "positional",
		Rule:       "every command declares its positional contract, so a blank identifier, an unexpected positional and an unknown subcommand are all refused before the command runs",
		AllowEmpty: true,
		Sites:      undeclaredPositionalSites(rootCmd),
	}
}

// TestPositionalSurfaceIsClosed — a command added without a contract fails the
// build the day it appears, instead of inheriting cobra's ArbitraryArgs and
// silently swallowing whatever it is handed.
func TestPositionalSurfaceIsClosed(t *testing.T) {
	root := surfaceRepoRoot(t)
	s := positionalSurface()
	m, err := surfaceaudit.LoadManifest(root, s.Name)
	if err != nil {
		t.Fatalf("loading the positional manifest: %v", err)
	}
	tests, err := testaudit.ScanRepo(root)
	if err != nil {
		t.Fatalf("indexing the test corpus: %v", err)
	}
	byName := make(map[string]bool, len(tests))
	for _, tc := range tests {
		byName[tc.Name] = true
	}
	res := surfaceaudit.Check(s, m, func(name string) bool { return byName[name] })
	if res.Failed() {
		t.Error(res.Report())
		return
	}
	t.Log(res.Report())
}

// TestPositionalExtractorFlagsAnUndeclaredCommand feeds the extractor a
// known-bad tree. Without it, a refactor that made contractOf always answer
// "takesNone" would leave the gate green forever with nothing behind it.
func TestPositionalExtractorFlagsAnUndeclaredCommand(t *testing.T) {
	fake := &cobra.Command{Use: "hactl"}
	silent := &cobra.Command{Use: "silent", Run: func(*cobra.Command, []string) {}}
	counted := &cobra.Command{Use: "counted", Args: cobra.ExactArgs(1), Run: func(*cobra.Command, []string) {}}
	declared := &cobra.Command{Use: "declared", Args: takes(1), Run: func(*cobra.Command, []string) {}}
	fake.AddCommand(silent, counted, declared)

	flagged := map[string]bool{}
	for _, s := range undeclaredPositionalSites(fake) {
		flagged[s.Key] = true
	}
	for _, want := range []string{"hactl", "hactl silent", "hactl counted"} {
		if !flagged[want] {
			t.Errorf("extractor did not flag %q, which declares no hactl contract", want)
		}
	}
	if flagged["hactl declared"] {
		t.Error("extractor flagged a command that does declare a contract")
	}
}

// TestNoCommandAcceptsABlankPositional is the universal the P1 asks for: not
// "auto show refuses an empty id" but "nothing in the tree accepts one". Each
// command is driven through the real entry point with one, two and three blank
// arguments, and the refusal has to come from the contract — an instance is
// deliberately not configured, so a command that got as far as talking to Home
// Assistant would fail with a different error and be caught here.
func TestNoCommandAcceptsABlankPositional(t *testing.T) {
	blanks := [][]string{{""}, {"", ""}, {" ", "\t", ""}}
	walkTree(rootCmd, func(c *cobra.Command) {
		args := strings.Fields(c.CommandPath())[1:]
		for _, blank := range blanks {
			full := append(append([]string{}, args...), blank...)
			out, err := runCLI(t, full...)
			if !errors.Is(err, errPositional) {
				t.Errorf("hactl %s: err = %v (out %.80q), want the positional contract to refuse it",
					strings.Join(full, " "), err, out)
			}
		}
	})
}

// TestEveryFamilyRefusesAnUnknownSubcommand is the third leg, quantified: every
// command that holds subcommands — the root, the twenty families, and `log`,
// which is runnable and has one — refuses a subcommand it does not have. Twelve
// families were found silently printing help at exit 0; nothing said whether
// the thirteenth did too.
func TestEveryFamilyRefusesAnUnknownSubcommand(t *testing.T) {
	groups := 0
	walkTree(rootCmd, func(c *cobra.Command) {
		if !c.HasSubCommands() {
			return
		}
		groups++
		args := append(append([]string{}, strings.Fields(c.CommandPath())[1:]...), "zzz-not-a-subcommand")
		out, err := runCLI(t, args...)
		if !errors.Is(err, errPositional) {
			t.Errorf("hactl %s: err = %v, want a refusal", strings.Join(args, " "), err)
		}
		if out != "" {
			t.Errorf("hactl %s printed %.60q to stdout while failing", strings.Join(args, " "), out)
		}
	})
	if groups < 20 {
		t.Fatalf("only %d commands with subcommands found — the walk has stopped matching", groups)
	}
}

// TestFamilyGroupsAreMarkedAsSuch pins the annotation three other walkers in
// this package depend on. `family` makes a group runnable so that cobra reaches
// its argument validator at all; the MCP gate, the --json sweep and the manual
// guardrail all ask "is this a real command?" with Runnable(), and would each
// gain twenty commands to classify, document and answer --json for if the mark
// were dropped.
func TestFamilyGroupsAreMarkedAsSuch(t *testing.T) {
	var unmarked []string
	walkTree(rootCmd, func(c *cobra.Command) {
		if c.HasSubCommands() && c.CommandPath() != "hactl log" && !isFamilyGroup(c) {
			unmarked = append(unmarked, c.CommandPath())
		}
		if isFamilyGroup(c) && !c.Runnable() {
			t.Errorf("%s is marked as a family group but is not runnable — cobra never reaches its Args", c.CommandPath())
		}
	})
	if len(unmarked) > 0 {
		t.Errorf("commands that group subcommands but are not marked with family(): %s\n"+
			"wrap the declaration: var xCmd = family(&cobra.Command{...})", strings.Join(unmarked, ", "))
	}
}
